server:
  address: localhost
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true

  error:
    whitelabel:
      enabled: false

#  tomcat:
#    basedir:

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8"
    username: "root"
    password: "123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"


  profiles:
    active: "dev"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false

  #    show-sql: true

  #    hibernate:
  #      ddl-auto: "none"
  #      use-new-id-generator-mappings: false
  #
  #    properties:
  #      hibernate:
  #        generate_statistics: true
  #        current_session_context_class: "thread"
  #        jdbc:
  #          batch_size: 10
  #        format_sql: true
  #        connection:
  #          autocommit: false

  thymeleaf:
    render-hidden-markers-before-checkboxes: true
    cache: false

  liquibase:
    enabled: false
  #    change-log: classpath:db.changelog/db.changelog-master.xml
  #    url: jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    user: root
  #    password: 123

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  web:
    resources:
      #      включаем css и проч.
      add-mappings: true

  mvc:
    throw-exception-if-no-handler-found: true

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 0

  mail:
    host: smtp.yandex.ru
    username: s@y.ru
    password: 123
    port: 587
    protocol: smtp

#  main:
#    allow-bean-definition-overriding: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:log4j2.properties
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO

jwt:
  header: Authorization
  secret: authsecret
  #  expiration: 3600000
  #  refresh: 86400000
  ## For test
  expiration: 60000
  refresh: 120000
