server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8
    username: root
    password: Zerkalo82
    driverClassName: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  thymeleaf:
    render-hidden-markers-before-checkboxes: true

#  liquibase:
#    change-log: classpath:/db.changelog/db.changelog-master.xml
#    url: jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    user: root
#    password: Zerkalo82

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#logging:
#  config: src/main/resources/log4j2.properties
