server:
  address: localhost
  port: 8080
  compression:
    enabled: true
  http2:
      enabled: true

  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8"
    username: "root"
    password: "Zerkalo82"
    driver-class-name: "com.mysql.cj.jdbc.Driver"


  profiles:
    active: "dev"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true
#    show-sql: true

#    hibernate:
#      ddl-auto: "none"
#      use-new-id-generator-mappings: false
#
#    properties:
#      hibernate:
#        generate_statistics: true
#        current_session_context_class: "thread"
#        jdbc:
#          batch_size: 10
#        format_sql: true
#        connection:
#          autocommit: false

  thymeleaf:
    render-hidden-markers-before-checkboxes: true
    cache: false

  liquibase:
    enabled: false
#    change-log: classpath:db.changelog/db.changelog-master.xml
#    url: jdbc:mysql://localhost:3306/test7_001?characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    user: root
#    password: Zerkalo82

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:log4j2.properties
  level:
    ROOT: INFO
    org:
      springframework.web: INFO
      hibernate: INFO
