databaseChangeLog:
  - changeSet:
      id: dev1
      author: m
      changes:
        - createTable:
            tableName: users
            remarks: Пользователи
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    primaryKeyName: users_pk
                    nullable: false
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: password
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                  defaultValue: "ACTIVE"
              - column:
                  name: role
                  type: VARCHAR(20)
                  constraints:
                    nullable: false
                  defaultValue: "USER"
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP